version: "3.6"
services:
  back:
    stdin_open: true
    tty: true
    command: >
      sh -c "npm start"
  front-books:
    depends_on:
      - api
    command: >
      sh -c "npm start"
    stdin_open: true
    tty: true
  front-selections:
    depends_on:
      - api
    command: >
      sh -c "npm start"
    stdin_open: true
    tty: true
